# Generated by Django 4.0.1 on 2022-01-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='narx',
            new_name='kelgan_narxi',
        ),
        migrations.AddField(
            model_name='product',
            name='sotuvdagi_narx',
            field=models.IntegerField(default=10000),
            preserve_default=False,
        ),
    ]
